/* LLYWords — the daily prophetic word list for prophetic-word.html.
 *
 * Tone: encouragement. Every word is written to build up, comfort, and strengthen
 * (1 Corinthians 14:3). No rebuke, no shame, no correction framing.
 *
 * Scripture translation: World English Bible (public domain).
 * House style: the divine name rendered "Yahweh" in the WEB Old Testament is set as
 * "God"; "Lord" and "LORD" are left exactly as they appear.
 *
 * HOW THE PAGE PICKS A WORD
 * The page cycles this list on repeat, one entry per day in US Central time. When you
 * add entries, the cycle simply gets longer. Nothing else has to change.
 *
 * TO ADD A NEW WORD
 * Append an object to the end of this array. All five fields are required:
 *   word       the prophetic word itself (the large text on the blue card)
 *   scripture  the verse text, WEB, without quote marks (the page adds them)
 *   ref        the citation, e.g. "Jeremiah 17:8" (the page adds " · WEB")
 *   prayer     a short prayer, 1-2 sentences
 *   carry      one encouraging thing to do or hold onto today
 *
 * The "Previous Prophetic Words" cards show the first sentence of `word`, so make the
 * first sentence able to stand on its own. Save the file; the site picks it up on the
 * next page load.
 */
window.LLYWords = [
{word:"The ground you have been praying over is not barren. What you planted in the quiet season is rooting deeper than you can see, and this is the month the roots find water. Keep watering it; the harvest is on its way.",scripture:"For he will be as a tree planted by the waters, who spreads out its roots by the river.",ref:"Jeremiah 17:8",prayer:"Father, thank You for the growth happening underground. Give me joy in the waiting and eyes to see the first green.",carry:"Name one thing you have been faithful in. Thank Him for it out loud."},
{word:"Your steadiness is being noticed in heaven. The quiet, ordinary faithfulness you show where God placed you is building something that will hold weight for years.",scripture:"And that you make it your ambition to lead a quiet life, and to do your own business, and to work with your own hands.",ref:"1 Thessalonians 4:11",prayer:"Lord, thank You that nothing done for You is small. Let my ordinary day be worship.",carry:"Do one ordinary task today as an offering and enjoy it."},
{word:"He is opening something new, and it will not look like what you asked for because it is better fitted to who you are becoming. Look up; the path is already forming.",scripture:"Behold, I will do a new thing. It springs forth now. Don't you know it?",ref:"Isaiah 43:19",prayer:"God, thank You for the new thing. Give me an open heart to receive it in whatever form it comes.",carry:"Write down one hope you have set aside and invite Him into it again."},
{word:"Freedom is available to you today. The weight you have carried in that old memory can be set down, and He will carry what you release.",scripture:"Bearing with one another, and forgiving each other, if any man has a complaint against anyone; even as Christ forgave you, so you also do.",ref:"Colossians 3:13",prayer:"Father, thank You for the freedom You bought. I hand You what I have been holding and receive Your peace.",carry:"Speak one blessing over someone you once found hard to bless."},
{word:"Provision is already on the road toward you. Keep your hands open and your heart light; what He sends will arrive in time and often in ordinary clothing.",scripture:"My God will supply every need of yours according to his riches in glory in Christ Jesus.",ref:"Philippians 4:19",prayer:"Lord, thank You for what is already coming. Keep me grateful before it arrives and generous after.",carry:"Thank Him out loud for one thing you do not have yet."},
{word:"He delights in your plans and He wants to be in them with you. Bring Him the whole dream today, and watch Him add what you could not.",scripture:"Commit your deeds to God, and your plans shall succeed.",ref:"Proverbs 16:3",prayer:"God, thank You that You care about what I am building. Lead me and I will follow gladly.",carry:"Talk to Him about your plan the way you would talk to a friend who wants to help."},
{word:"Your prayers for your family are safe with Him. Every one you have whispered is kept, remembered, and still working.",scripture:"Golden bowls full of incense, which are the prayers of the saints.",ref:"Revelation 5:8",prayer:"Father, thank You that not one prayer is lost. Keep working in the people I love.",carry:"Pray one sentence of blessing over someone in your family."},
{word:"The wait is not wasted. He is preparing you and the answer at the same time, and both will be ready together.",scripture:"Let us not be weary in doing good, for we will reap in due season, if we don't give up.",ref:"Galatians 6:9",prayer:"Lord, thank You for what You are forming in me. Give me strength and good cheer for today.",carry:"Notice one way you have grown in the waiting and thank Him for it."},
{word:"You belong in the room He placed you in. Take up your space with gentleness and confidence; your voice was part of the assignment.",scripture:"God has not given us a spirit of fear, but of power, love, and self-control.",ref:"2 Timothy 1:7",prayer:"God, thank You for calling me here. Give me courage that is kind and words that help.",carry:"Offer the good idea you have been holding back."},
{word:"He is glad to meet you first thing. The morning belongs to Him, and He has something for you before the day makes its demands.",scripture:"In the morning, my prayer comes before you.",ref:"Psalm 88:13",prayer:"Father, thank You for meeting me early. Speak, and I will listen.",carry:"Give Him the first ten minutes tomorrow and simply enjoy His company."},
{word:"He is tending your friendships with more care than you can. Some are being restored, some are being rested, and He is faithful in both.",scripture:"For everything there is a season, and a time for every purpose under heaven.",ref:"Ecclesiastes 3:1",prayer:"Lord, thank You for the people You have given me. Bless them and lead me to the ones You are bringing.",carry:"Reach out to one person simply to encourage them."},
{word:"Rest is His gift to you, not a reward you have to earn. Lay it down today and find that He has been holding it the whole time.",scripture:"Come to me, all you who labor and are heavily burdened, and I will give you rest.",ref:"Matthew 11:28",prayer:"God, thank You for rest. Teach me to receive it without guilt.",carry:"Put one thing down today and enjoy the quiet it leaves behind."},
{word:"His mercy is new this morning, and it is not rationed. You can begin again today with a clean heart and no speech about yesterday.",scripture:"His compassions don't fail. They are new every morning.",ref:"Lamentations 3:22-23",prayer:"Father, thank You for mercy that does not run out. I begin again with joy.",carry:"Restart one good habit at the smallest, easiest size."},
{word:"Your words over your home carry real power to build. What you speak in kindness today will still be standing years from now.",scripture:"Death and life are in the power of the tongue; those who love it will eat its fruit.",ref:"Proverbs 18:21",prayer:"Lord, thank You for the gift of words. Let my family hear life from me.",carry:"Speak one specific blessing over each person you live with."},
{word:"You are exactly on time in your own field. He is not measuring your season against anyone else's harvest, and neither should you.",scripture:"Each man should test his own work. Then he will have reason for boasting in himself, and not in someone else.",ref:"Galatians 6:4",prayer:"God, thank You for my row. Show me the good work in front of me and let me enjoy it.",carry:"List three things growing in your life right now."},
{word:"He is a healer, and He is near to the tender place you have protected. You can bring it to Him and be met with gentleness.",scripture:"He heals the broken in heart, and binds up their wounds.",ref:"Psalm 147:3",prayer:"Father, thank You for Your kindness. Come close to the part of me that is still healing.",carry:"Tell Him honestly how you feel and rest a moment in His answer."},
{word:"Generosity is a door into joy. What you give this week will come back to you in ways you will not be able to trace.",scripture:"Give, and it will be given to you: good measure, pressed down, shaken together, and running over.",ref:"Luke 6:38",prayer:"Lord, thank You for everything in my hands. Show me who to bless this week.",carry:"Give something away today and enjoy doing it."},
{word:"His guidance is a kindness, never a shaming. When He shows you a better way, it is because He is protecting your future.",scripture:"For whom God loves, he disciplines, and chastises every son whom he receives.",ref:"Hebrews 12:6",prayer:"God, thank You for loving me enough to lead me. I trust the direction You are giving.",carry:"Take the one step He has been gently showing you."},
{word:"Perfect love is making room in you where fear used to live. You can make today's decision from peace instead of pressure.",scripture:"There is no fear in love; but perfect love casts out fear.",ref:"1 John 4:18",prayer:"Father, thank You that Your love is bigger than my fear. Let love lead me today.",carry:"Make one decision today from peace and notice how it feels."},
{word:"You know enough to take the next step, and He will meet you on the road with the rest. The path lights up as you walk it.",scripture:"Trust in God with all your heart, and don't lean on your own understanding.",ref:"Proverbs 3:5",prayer:"Lord, thank You for guiding me one step at a time. I will move on what I know.",carry:"Take the step in front of you before you understand the one after it."},
{word:"The gift in you is still alive and still yours. He gave it on purpose, for a season exactly like this one.",scripture:"For this cause I remind you that you should stir up the gift of God which is in you.",ref:"2 Timothy 1:6",prayer:"God, thank You for what You placed in me. Give me a place to use it this week.",carry:"Use your gift once today, joyfully, without needing it to be perfect."},
{word:"Peace is available inside the situation, not only after it. He is offering to guard your mind today while the outcome is still unfolding.",scripture:"The peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",ref:"Philippians 4:7",prayer:"Father, thank You for peace that does not depend on the outcome. Guard my mind today.",carry:"When the anxious thought comes, hand it to Him in one sentence."},
{word:"He wants the real you, not the polished version. The prayer you think is too raw is the one He has been waiting to hear.",scripture:"Pour out your heart before him. God is a refuge for us.",ref:"Psalm 62:8",prayer:"Lord, thank You that I can come as I am. Here is what I actually feel.",carry:"Pray one honest, unedited sentence today."},
{word:"Honor the small beginning; He does. What starts this week looks modest on purpose, so that its growth is unmistakably His.",scripture:"Who despises this day of small things?",ref:"Zechariah 4:10",prayer:"God, thank You for small starts. Help me celebrate the first step as much as the last.",carry:"Begin the small version of the thing you have been dreaming about."},
{word:"He is able to give you peace with people without asking you to carry what is not yours. Your part can be light today.",scripture:"If it is possible, as much as it is up to you, be at peace with all men.",ref:"Romans 12:18",prayer:"Father, thank You for peace. Give me wisdom and a soft heart at the same time.",carry:"Do your part in one relationship and leave the rest with Him."},
{word:"Look at who He has already placed beside you. The help you have been praying for may already be sitting at your table.",scripture:"Two are better than one, because they have a good reward for their labor.",ref:"Ecclesiastes 4:9",prayer:"Lord, thank You for the people You sent. Help me receive help with gladness.",carry:"Ask one person for the specific help you need."},
{word:"Your worship changes the atmosphere before it changes the circumstance. Sing today and watch the room get lighter.",scripture:"About midnight Paul and Silas were praying and singing hymns to God, and the prisoners were listening to them.",ref:"Acts 16:25",prayer:"God, thank You that praise is always available. I will worship You right in the middle of today.",carry:"Play one worship song during the busiest part of your day."},
{word:"He gives courage to match the clarity He gives. What He showed you, He will also strengthen you to do.",scripture:"Therefore let's also lay aside every weight and the sin which so easily entangles us, and let's run with patience the race that is set before us.",ref:"Hebrews 12:1",prayer:"Father, thank You for clarity. Now give me the courage to walk in it with peace.",carry:"Take one brave, kind action toward what He has shown you."},
{word:"He sees the work no one has thanked you for. Your reward is secure with Him and it does not depend on anyone noticing.",scripture:"Whatever you do, work heartily, as for the Lord, and not for men.",ref:"Colossians 3:23",prayer:"Lord, thank You that You see everything. I offer today's work to You.",carry:"Do the unseen work today as worship and let that be enough."},
{word:"His promises over your children are stronger than your fears for them. Pray what you want to see; He is listening.",scripture:"All your children shall be taught by God, and your children's peace shall be great.",ref:"Isaiah 54:13",prayer:"Father, thank You for Your promises over my children. I speak those promises today.",carry:"Pray one specific promise over a child by name."},
{word:"You can grieve and be held at the same time. He is not asking you to hurry; He is sitting with you in it.",scripture:"Blessed are those who mourn, for they shall be comforted.",ref:"Matthew 5:4",prayer:"God, thank You for staying close. Comfort me in the way only You can.",carry:"Let yourself feel it honestly for a few minutes and let Him be near."},
{word:"Caring for your body is a way of honoring Him. Small, kind consistency will do more than any burst of intensity.",scripture:"Or don't you know that your body is a temple of the Holy Spirit who is in you?",ref:"1 Corinthians 6:19",prayer:"Lord, thank You for this body. Teach me to care for it with kindness.",carry:"Do one small, good physical thing today and repeat it tomorrow."},
{word:"Influence is growing in you through service. The low seat you have taken is the very place He is preparing to raise.",scripture:"Whoever desires to become great among you shall be your servant.",ref:"Matthew 20:26",prayer:"Father, thank You for making me useful. Let me serve with joy today.",carry:"Serve someone in a way no one will record."},
{word:"He gives wisdom generously about what you steward, including your finances. Look at the numbers with Him and you will not be afraid of them.",scripture:"Know well the condition of your flocks, and pay attention to your herds.",ref:"Proverbs 27:23",prayer:"God, thank You for wisdom. Sit with me while I look, and show me the next good step.",carry:"Look at one number honestly and thank Him for the clarity."},
{word:"What He is closing, He closes in kindness, and what He is opening is worth your full attention. Turn your face forward.",scripture:"Don't remember the former things, and don't consider the things of old.",ref:"Isaiah 43:18",prayer:"Lord, thank You for both the ending and the beginning. Help me walk into what is next with hope.",carry:"Name one thing you are looking forward to and thank Him for it."},
{word:"He built rest into your week as a gift. The work will still be there, and you will be stronger when you return to it.",scripture:"Remember the Sabbath day, to keep it holy.",ref:"Exodus 20:8",prayer:"Father, thank You for the gift of a day. Teach me to enjoy it with You.",carry:"Choose your day of rest this week and protect it happily."},
{word:"The prayer you stopped praying is still open before Him. Nothing offered in faith has ever been thrown away.",scripture:"This is the boldness which we have toward him, that if we ask anything according to his will, he listens to us.",ref:"1 John 5:14",prayer:"God, thank You for hearing me every time. I bring it to You again with hope.",carry:"Pray the old prayer once more, out loud, with expectation."},
{word:"You are not fighting alone, and the outcome is not resting on your strength. He goes ahead of you and stands beside you.",scripture:"For our wrestling is not against flesh and blood, but against the principalities, against the powers.",ref:"Ephesians 6:12",prayer:"Lord, thank You that the battle is Yours. Give me discernment and peace today.",carry:"Pray over the situation once instead of replaying it."},
{word:"Truth spoken in love always makes room for something better. The conversation you are praying about can be a doorway, not a loss.",scripture:"Speaking truth in love, we may grow up in all things into him.",ref:"Ephesians 4:15",prayer:"Father, thank You for grace in my mouth. Give me words that are honest and kind.",carry:"Have the conversation gently, and trust Him with the response."},
{word:"He has not changed His mind about you. The call on your life is steady, and He is glad to have you walking in it again today.",scripture:"For the gifts and the calling of God are irrevocable.",ref:"Romans 11:29",prayer:"God, thank You that Your call does not depend on my performance. Here I am; send me.",carry:"Take one small step back toward what He called you to."}
];
