/* LLYVerses — the 365-day verse list for the Verse of the Day page.
 *
 * Translation: World English Bible (public domain).
 * House style: the divine name rendered "Yahweh" in the WEB Old Testament is set as "God";
 * "Lord" and "LORD" are left exactly as they appear.
 *
 * n    day of the year (1–365). Day 366 in a leap year repeats day 365.
 * ref  citation shown under the verse
 * text the verse itself
 *
 * Numbering matches the social-media graphic files in uploads/ — day 001 is
 * 001-john-3-16.png, day 003 is 003-philippians-4-13.png, and so on.
 */
window.LLYVerses = [
{n:1,ref:"John 3:16",text:"For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life."},
{n:2,ref:"Jeremiah 29:11",text:"For I know the thoughts that I think toward you, says God, thoughts of peace, and not of evil, to give you hope and a future."},
{n:3,ref:"Philippians 4:13",text:"I can do all things through Christ, who strengthens me."},
{n:4,ref:"Romans 8:28",text:"We know that all things work together for good for those who love God, for those who are called according to his purpose."},
{n:5,ref:"Isaiah 41:10",text:"Don't be afraid, for I am with you. Don't be dismayed, for I am your God. I will strengthen you. Yes, I will help you."},
{n:6,ref:"Proverbs 3:5",text:"Trust in God with all your heart, and don't lean on your own understanding."},
{n:7,ref:"Proverbs 21:21",text:"He who follows after righteousness and loving kindness finds life, righteousness, and honor."},
{n:8,ref:"Psalm 23:1",text:"God is my shepherd; I shall lack nothing."},
{n:9,ref:"Psalm 23:4",text:"Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me."},
{n:10,ref:"Matthew 11:28",text:"Come to me, all you who labor and are heavily burdened, and I will give you rest."},
{n:11,ref:"Joshua 1:9",text:"Haven't I commanded you? Be strong and courageous. Don't be afraid. Don't be dismayed, for God your God is with you wherever you go."},
{n:12,ref:"Psalm 46:1",text:"God is our refuge and strength, a very present help in trouble."},
{n:13,ref:"2 Corinthians 5:17",text:"Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new."},
{n:14,ref:"Galatians 2:20",text:"I have been crucified with Christ, and it is no longer I that live, but Christ living in me."},
{n:15,ref:"Ephesians 2:8",text:"For by grace you have been saved through faith, and that not of yourselves; it is the gift of God."},
{n:16,ref:"Hebrews 11:1",text:"Now faith is assurance of things hoped for, proof of things not seen."},
{n:17,ref:"John 14:6",text:"Jesus said to him, I am the way, the truth, and the life. No one comes to the Father, except through me."},
{n:18,ref:"Romans 12:2",text:"Don't be conformed to this world, but be transformed by the renewing of your mind."},
{n:19,ref:"Psalm 119:105",text:"Your word is a lamp to my feet, and a light for my path."},
{n:20,ref:"Isaiah 40:31",text:"But those who wait for God will renew their strength. They will mount up with wings like eagles."},
{n:21,ref:"Matthew 6:33",text:"But seek first God's Kingdom and his righteousness; and all these things will be given to you as well."},
{n:22,ref:"1 John 4:7",text:"Beloved, let's love one another, for love is of God; and everyone who loves has been born of God and knows God."},
{n:23,ref:"Psalm 27:1",text:"God is my light and my salvation. Whom shall I fear? God is the strength of my life. Of whom shall I be afraid?"},
{n:24,ref:"Romans 10:9",text:"If you will confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved."},
{n:25,ref:"2 Timothy 1:7",text:"For God didn't give us a spirit of fear, but of power, love, and self-control."},
{n:26,ref:"Philippians 4:6",text:"In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God."},
{n:27,ref:"Philippians 4:7",text:"And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus."},
{n:28,ref:"Psalm 91:1",text:"He who dwells in the secret place of the Most High will rest in the shadow of the Almighty."},
{n:29,ref:"1 Peter 5:7",text:"Cast all your worries on him, because he cares for you."},
{n:30,ref:"Isaiah 30:15",text:"In returning and rest you will be saved. In quietness and in confidence will be your strength."},
{n:31,ref:"Lamentations 3:22-23",text:"His compassions never fail. They are new every morning. Great is your faithfulness."},
{n:32,ref:"Colossians 3:23",text:"And whatever you do, work heartily, as for the Lord, and not for men."},
{n:33,ref:"Hebrews 13:8",text:"Jesus Christ is the same yesterday, today, and forever."},
{n:34,ref:"Matthew 5:16",text:"Even so, let your light shine before men, that they may see your good works and glorify your Father who is in heaven."},
{n:35,ref:"Psalm 37:4",text:"Also delight yourself in God, and he will give you the desires of your heart."},
{n:36,ref:"Proverbs 18:10",text:"God's name is a strong tower: the righteous run to him, and are safe."},
{n:37,ref:"Isaiah 26:3",text:"You will keep whoever's mind is steadfast in perfect peace, because he trusts in you."},
{n:38,ref:"John 8:32",text:"You will know the truth, and the truth will make you free."},
{n:39,ref:"Romans 5:8",text:"But God commends his own love toward us, in that while we were yet sinners, Christ died for us."},
{n:40,ref:"1 Corinthians 10:13",text:"God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape."},
{n:41,ref:"Psalm 34:8",text:"Oh taste and see that God is good. Blessed is the man who takes refuge in him."},
{n:42,ref:"Psalm 34:18",text:"God is near to those who have a broken heart, and saves those who have a crushed spirit."},
{n:43,ref:"Micah 6:8",text:"He has shown you, O man, what is good. What does God require of you, but to act justly, to love mercy, and to walk humbly with your God?"},
{n:44,ref:"Ephesians 4:32",text:"And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you."},
{n:45,ref:"Colossians 4:2",text:"Continue steadfastly in prayer, watching in it with thanksgiving."},
{n:46,ref:"Galatians 5:22-23",text:"But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law."},
{n:47,ref:"James 1:2",text:"Count it all joy, my brothers, when you fall into various temptations."},
{n:48,ref:"James 1:5",text:"But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him."},
{n:49,ref:"Psalm 121:1",text:"I will lift up my eyes to the hills. Where does my help come from?"},
{n:50,ref:"Psalm 121:2",text:"My help comes from God, who made heaven and earth."},
{n:51,ref:"Deuteronomy 31:6",text:"Be strong and courageous. Don't be afraid or scared of them; for God your God himself is who goes with you. He will not fail you nor forsake you."},
{n:52,ref:"Isaiah 43:2",text:"When you pass through the waters, I will be with you, and through the rivers, they will not overflow you."},
{n:53,ref:"John 16:33",text:"In the world you have trouble; but cheer up! I have overcome the world."},
{n:54,ref:"Romans 15:13",text:"Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope in the power of the Holy Spirit."},
{n:55,ref:"Psalm 51:10",text:"Create in me a clean heart, O God. Renew a right spirit within me."},
{n:56,ref:"Proverbs 16:3",text:"Commit your deeds to God, and your plans shall succeed."},
{n:57,ref:"Matthew 28:19",text:"Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit."},
{n:58,ref:"Matthew 28:20",text:"Behold, I am with you always, even to the end of the age."},
{n:59,ref:"Psalm 112:7",text:"He will not be afraid of evil news. His heart is steadfast, trusting in God."},
{n:60,ref:"1 Thessalonians 5:16-18",text:"Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you."},
{n:61,ref:"Psalm 18:2",text:"God is my rock, my fortress, and my deliverer; my God, my rock, in whom I take refuge."},
{n:62,ref:"Psalm 18:32",text:"The God who arms me with strength, and makes my way perfect."},
{n:63,ref:"Nahum 1:7",text:"God is good, a stronghold in the day of trouble; and he knows those who take refuge in him."},
{n:64,ref:"Zephaniah 3:17",text:"God, your God, is among you, a mighty one who will save. He will rejoice over you with joy."},
{n:65,ref:"Hebrews 4:16",text:"Let's therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need."},
{n:66,ref:"1 John 1:9",text:"If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness."},
{n:67,ref:"Revelation 21:4",text:"He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more."},
{n:68,ref:"Psalm 139:14",text:"I will give thanks to you, for I am fearfully and wonderfully made. Your works are wonderful."},
{n:69,ref:"Psalm 139:23",text:"Search me, God, and know my heart. Try me, and know my thoughts."},
{n:70,ref:"Isaiah 55:8",text:"For my thoughts are not your thoughts, and your ways are not my ways, says God."},
{n:71,ref:"Jeremiah 33:3",text:"Call to me, and I will answer you, and will show you great and difficult things, which you don't know."},
{n:72,ref:"Ezekiel 36:26",text:"I will give you a new heart, and I will put a new spirit within you."},
{n:73,ref:"Matthew 5:14",text:"You are the light of the world. A city located on a hill can't be hidden."},
{n:74,ref:"Mark 11:24",text:"Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them."},
{n:75,ref:"Luke 1:37",text:"For nothing spoken by God is impossible."},
{n:76,ref:"John 1:1",text:"In the beginning was the Word, and the Word was with God, and the Word was God."},
{n:77,ref:"John 10:10",text:"I came that they may have life, and may have it abundantly."},
{n:78,ref:"John 15:5",text:"I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing."},
{n:79,ref:"Acts 1:8",text:"But you will receive power when the Holy Spirit has come upon you. You will be witnesses to me."},
{n:80,ref:"Romans 6:23",text:"For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."},
{n:81,ref:"Romans 8:1",text:"There is therefore now no condemnation to those who are in Christ Jesus."},
{n:82,ref:"Romans 8:31",text:"What then shall we say about these things? If God is for us, who can be against us?"},
{n:83,ref:"Romans 8:38",text:"For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come."},
{n:84,ref:"Romans 8:39",text:"Nor height, nor depth, nor any other created thing will be able to separate us from God's love which is in Christ Jesus our Lord."},
{n:85,ref:"1 Corinthians 13:4",text:"Love is patient and is kind. Love doesn't envy. Love doesn't brag, is not proud."},
{n:86,ref:"1 Corinthians 13:7",text:"Love bears all things, believes all things, hopes all things, endures all things."},
{n:87,ref:"1 Corinthians 13:13",text:"But now faith, hope, and love remain, these three. The greatest of these is love."},
{n:88,ref:"2 Corinthians 12:9",text:"My grace is sufficient for you, for my power is made perfect in weakness."},
{n:89,ref:"Galatians 6:9",text:"Let's not be weary in doing good, for we will reap in due season, if we don't give up."},
{n:90,ref:"Ephesians 2:10",text:"For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them."},
{n:91,ref:"Ephesians 6:10",text:"Finally, be strong in the Lord and in the strength of his might."},
{n:92,ref:"Ephesians 6:11",text:"Put on the whole armor of God, that you may be able to stand against the wiles of the devil."},
{n:93,ref:"Philippians 1:6",text:"Being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ."},
{n:94,ref:"Philippians 2:3",text:"Doing nothing through rivalry or through conceit, but in humility, each counting others better than himself."},
{n:95,ref:"Philippians 4:8",text:"Whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, think about these things."},
{n:96,ref:"Philippians 4:19",text:"My God will supply every need of yours according to his riches in glory in Christ Jesus."},
{n:97,ref:"Colossians 3:2",text:"Set your mind on the things that are above, not on the things that are on the earth."},
{n:98,ref:"Ephesians 5:20",text:"Giving thanks always concerning all things in the name of our Lord Jesus Christ to God, even the Father."},
{n:99,ref:"2 Timothy 3:16",text:"Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness."},
{n:100,ref:"Hebrews 12:1",text:"Let's lay aside every weight and the sin which so easily entangles us, and let's run with perseverance the race that is set before us."},
{n:101,ref:"Hebrews 12:2",text:"Let us look to Jesus, the author and perfecter of faith, who for the joy that was set before him endured the cross."},
{n:102,ref:"James 1:22",text:"But be doers of the word, and not only hearers, deluding your own selves."},
{n:103,ref:"James 4:7",text:"Be subject therefore to God. Resist the devil, and he will flee from you."},
{n:104,ref:"James 4:8",text:"Draw near to God, and he will draw near to you."},
{n:105,ref:"1 Peter 2:9",text:"But you are a chosen race, a royal priesthood, a holy nation, a people for God's own possession."},
{n:106,ref:"1 Peter 5:8",text:"Be sober and self-controlled. Be watchful."},
{n:107,ref:"2 Peter 3:9",text:"The Lord is not slow concerning his promise, but is patient with us, not wishing that anyone should perish."},
{n:108,ref:"1 John 3:1",text:"See how great a love the Father has given to us, that we should be called children of God!"},
{n:109,ref:"1 John 4:18",text:"There is no fear in love; but perfect love casts out fear."},
{n:110,ref:"1 John 4:19",text:"We love him, because he first loved us."},
{n:111,ref:"Revelation 3:20",text:"Behold, I stand at the door and knock. If anyone hears my voice and opens the door, then I will come in to him."},
{n:112,ref:"Genesis 1:1",text:"In the beginning, God created the heavens and the earth."},
{n:113,ref:"Exodus 14:14",text:"God will fight for you, and you shall be still."},
{n:114,ref:"Exodus 15:2",text:"God is my strength and song. He has become my salvation."},
{n:115,ref:"Psalm 16:11",text:"You will show me the path of life. In your presence is fullness of joy. In your right hand there are pleasures forever more."},
{n:116,ref:"Psalm 119:165",text:"Those who love your law have great peace. Nothing causes them to stumble."},
{n:117,ref:"Numbers 6:24-26",text:"God bless you and keep you. God make his face to shine on you and be gracious to you. God lift up his face toward you and give you peace."},
{n:118,ref:"Deuteronomy 6:5",text:"You shall love God your God with all your heart, with all your soul, and with all your might."},
{n:119,ref:"Deuteronomy 31:8",text:"God himself is who goes before you. He will be with you. He will not fail you nor forsake you. Don't be afraid. Don't be discouraged."},
{n:120,ref:"1 Samuel 16:7",text:"For man looks at the outward appearance, but God looks at the heart."},
{n:121,ref:"2 Chronicles 7:14",text:"If my people, who are called by my name, will humble themselves, pray, seek my face, and turn from their wicked ways, then I will hear from heaven."},
{n:122,ref:"Nehemiah 8:10",text:"Don't be grieved, for the joy of God is your strength."},
{n:123,ref:"Job 19:25",text:"But as for me, I know that my Redeemer lives."},
{n:124,ref:"Psalm 1:1",text:"Blessed is the man who doesn't walk in the counsel of the wicked, nor stand on the path of sinners."},
{n:125,ref:"Psalm 1:3",text:"He will be like a tree planted by the streams of water, that produces its fruit in its season."},
{n:126,ref:"Psalm 16:8",text:"I have set God always before me. Because he is at my right hand, I shall not be moved."},
{n:127,ref:"Psalm 19:1",text:"The heavens declare the glory of God. The expanse shows his handiwork."},
{n:128,ref:"Psalm 19:14",text:"Let the words of my mouth and the meditation of my heart be acceptable in your sight, God, my rock, and my redeemer."},
{n:129,ref:"Psalm 27:14",text:"Wait for God. Be strong, and let your heart take courage. Yes, wait for God."},
{n:130,ref:"Psalm 28:7",text:"God is my strength and my shield. My heart has trusted in him, and I am helped."},
{n:131,ref:"Psalm 30:5",text:"Weeping may stay for the night, but joy comes in the morning."},
{n:132,ref:"Psalm 32:7",text:"You are my hiding place. You will preserve me from trouble. You will surround me with songs of deliverance."},
{n:133,ref:"Psalm 32:8",text:"I will instruct you and teach you in the way which you shall go. I will counsel you with my eye on you."},
{n:134,ref:"Psalm 33:4",text:"For God's word is right. All his work is done in faithfulness."},
{n:135,ref:"Psalm 34:4",text:"I sought God, and he answered me, and delivered me from all my fears."},
{n:136,ref:"Psalm 37:23",text:"A man's goings are established by God. He delights in his way."},
{n:137,ref:"Psalm 40:1",text:"I waited patiently for God. He turned to me, and heard my cry."},
{n:138,ref:"Psalm 42:1",text:"As the deer pants for the water brooks, so my soul pants after you, God."},
{n:139,ref:"Psalm 42:11",text:"Why are you in despair, my soul? Hope in God! For I shall still praise him."},
{n:140,ref:"Psalm 46:10",text:"Be still, and know that I am God."},
{n:141,ref:"Psalm 55:22",text:"Cast your burden on God and he will sustain you. He will never allow the righteous to be moved."},
{n:142,ref:"Psalm 56:3",text:"When I am afraid, I will put my trust in you."},
{n:143,ref:"Psalm 62:1",text:"My soul rests in God alone. My salvation is from him."},
{n:144,ref:"Psalm 62:8",text:"Trust in him at all times, you people. Pour out your heart before him."},
{n:145,ref:"Psalm 63:1",text:"God, you are my God. I will earnestly seek you. My soul thirsts for you."},
{n:146,ref:"Psalm 71:5",text:"For you are my hope, Lord God, my confidence from my youth."},
{n:147,ref:"Psalm 73:26",text:"My flesh and my heart fails, but God is the strength of my heart and my portion forever."},
{n:148,ref:"Psalm 84:11",text:"For God is a sun and a shield. God will give grace and glory."},
{n:149,ref:"Psalm 86:15",text:"But you, Lord, are a merciful and gracious God, slow to anger, and abundant in loving kindness and truth."},
{n:150,ref:"Psalm 90:12",text:"So teach us to count our days, that we may gain a heart of wisdom."},
{n:151,ref:"Psalm 91:2",text:"I will say of God, He is my refuge and my fortress; my God, in whom I trust."},
{n:152,ref:"Psalm 91:11",text:"For he will put his angels in charge of you, to guard you in all your ways."},
{n:153,ref:"Psalm 94:19",text:"In the multitude of my thoughts within me, your comforts delight my soul."},
{n:154,ref:"Psalm 100:4",text:"Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name."},
{n:155,ref:"Psalm 103:2",text:"Praise God, my soul, and don't forget all his benefits."},
{n:156,ref:"Psalm 103:12",text:"As far as the east is from the west, so far has he removed our transgressions from us."},
{n:157,ref:"Psalm 107:1",text:"Give thanks to God, for he is good, for his loving kindness endures forever."},
{n:158,ref:"Psalm 118:24",text:"This is the day that God has made. We will rejoice and be glad in it!"},
{n:159,ref:"Psalm 119:11",text:"I have hidden your word in my heart, that I might not sin against you."},
{n:160,ref:"Psalm 121:8",text:"God will keep your going out and your coming in, from this time forward, and forever more."},
{n:161,ref:"Psalm 127:1",text:"Unless God builds the house, they who build it labor in vain."},
{n:162,ref:"Psalm 133:1",text:"See how good and how pleasant it is for brothers to live together in unity!"},
{n:163,ref:"Psalm 138:8",text:"God will fulfill that which concerns me. Your loving kindness, God, endures forever."},
{n:164,ref:"Psalm 143:8",text:"Cause me to hear your loving kindness in the morning, for I trust in you."},
{n:165,ref:"Psalm 145:18",text:"God is near to all those who call on him, to all who call on him in truth."},
{n:166,ref:"Psalm 147:3",text:"He heals the broken in heart, and binds up their wounds."},
{n:167,ref:"Proverbs 1:7",text:"The fear of God is the beginning of knowledge."},
{n:168,ref:"Proverbs 4:23",text:"Keep your heart with all diligence, for out of it is the wellspring of life."},
{n:169,ref:"Proverbs 11:25",text:"The liberal soul shall be made fat. He who waters shall be watered also himself."},
{n:170,ref:"Proverbs 15:1",text:"A gentle answer turns away wrath, but a harsh word stirs up anger."},
{n:171,ref:"Proverbs 17:17",text:"A friend loves at all times; and a brother is born for adversity."},
{n:172,ref:"Proverbs 19:21",text:"There are many plans in a man's heart, but God's counsel will prevail."},
{n:173,ref:"Proverbs 22:6",text:"Train up a child in the way he should go, and when he is old he will not depart from it."},
{n:174,ref:"Proverbs 27:17",text:"Iron sharpens iron; so a man sharpens his friend's countenance."},
{n:175,ref:"Proverbs 31:25",text:"Strength and dignity are her clothing. She laughs at the time to come."},
{n:176,ref:"Ecclesiastes 3:1",text:"For everything there is a season, and a time for every purpose under heaven."},
{n:177,ref:"Ecclesiastes 3:11",text:"He has made everything beautiful in its time."},
{n:178,ref:"Ecclesiastes 4:9",text:"Two are better than one, because they have a good reward for their labor."},
{n:179,ref:"Isaiah 1:18",text:"Come now, and let's reason together, says God: though your sins are as scarlet, they shall be as white as snow."},
{n:180,ref:"Isaiah 9:6",text:"For a child is born to us. A son is given to us; and the government will be on his shoulders."},
{n:181,ref:"Isaiah 30:21",text:"Your ears will hear a word behind you, saying, This is the way. Walk in it."},
{n:182,ref:"Isaiah 40:8",text:"The grass withers, the flower fades; but the word of our God stands forever."},
{n:183,ref:"Isaiah 40:29",text:"He gives power to the weak. He increases the strength of him who has no might."},
{n:184,ref:"Isaiah 41:13",text:"For I, your God, will hold your right hand, saying to you, Don't be afraid. I will help you."},
{n:185,ref:"Isaiah 43:19",text:"Behold, I will do a new thing. It springs out now. Don't you know it?"},
{n:186,ref:"Isaiah 53:5",text:"But he was pierced for our transgressions. He was crushed for our iniquities. The punishment that brought our peace was on him."},
{n:187,ref:"Isaiah 54:17",text:"No weapon that is formed against you will prevail."},
{n:188,ref:"Isaiah 58:11",text:"God will guide you continually, satisfy your soul in dry places, and make your bones strong."},
{n:189,ref:"Isaiah 61:1",text:"The Spirit of the Lord God is on me, because God has anointed me to preach good news to the humble."},
{n:190,ref:"Jeremiah 1:5",text:"Before I formed you in the womb, I knew you. Before you were born, I sanctified you."},
{n:191,ref:"Jeremiah 17:7",text:"Blessed is the man who trusts in God, and whose confidence is in God."},
{n:192,ref:"Jeremiah 17:8",text:"For he will be as a tree planted by the waters, who spreads out its roots by the river."},
{n:193,ref:"Jeremiah 31:3",text:"Yes, I have loved you with an everlasting love. Therefore I have drawn you with loving kindness."},
{n:194,ref:"Daniel 3:17",text:"If it happens, our God whom we serve is able to deliver us from the burning fiery furnace."},
{n:195,ref:"Joel 2:25",text:"I will restore to you the years that the swarming locust has eaten."},
{n:196,ref:"Habakkuk 3:19",text:"God, the Lord, is my strength. He makes my feet like deer's feet, and enables me to go in high places."},
{n:197,ref:"1 Corinthians 6:19",text:"Or don't you know that your body is a temple of the Holy Spirit who is in you, whom you have from God?"},
{n:198,ref:"1 Corinthians 6:20",text:"For you were bought with a price. Therefore glorify God in your body."},
{n:199,ref:"Malachi 3:10",text:"Bring the whole tithe into the storehouse, and test me now in this, says God of Armies, if I will not open you the windows of heaven."},
{n:200,ref:"Matthew 4:4",text:"Man shall not live by bread alone, but by every word that proceeds out of the mouth of God."},
{n:201,ref:"Matthew 5:6",text:"Blessed are those who hunger and thirst for righteousness, for they shall be filled."},
{n:202,ref:"Matthew 5:9",text:"Blessed are the peacemakers, for they shall be called children of God."},
{n:203,ref:"Matthew 6:21",text:"For where your treasure is, there your heart will be also."},
{n:204,ref:"Matthew 6:34",text:"Therefore don't be anxious for tomorrow, for tomorrow will be anxious for itself."},
{n:205,ref:"Matthew 7:7",text:"Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you."},
{n:206,ref:"Matthew 7:12",text:"Therefore whatever you desire for men to do to you, you shall also do to them."},
{n:207,ref:"Matthew 11:29",text:"Take my yoke upon you and learn from me, for I am gentle and lowly in heart; and you will find rest for your souls."},
{n:208,ref:"Matthew 16:24",text:"If anyone desires to come after me, let him deny himself, and take up his cross, and follow me."},
{n:209,ref:"Matthew 18:20",text:"For where two or three are gathered together in my name, there I am in the middle of them."},
{n:210,ref:"Matthew 19:26",text:"With men this is impossible, but with God all things are possible."},
{n:211,ref:"Matthew 22:37",text:"You shall love the Lord your God with all your heart, with all your soul, and with all your mind."},
{n:212,ref:"Matthew 22:39",text:"A second likewise is this, You shall love your neighbor as yourself."},
{n:213,ref:"Isaiah 32:17",text:"The work of righteousness will be peace, and the effect of righteousness, quietness and confidence forever."},
{n:214,ref:"Titus 2:11",text:"For the grace of God has appeared, bringing salvation to all men."},
{n:215,ref:"Psalm 40:8",text:"I delight to do your will, my God. Yes, your law is within my heart."},
{n:216,ref:"Luke 6:31",text:"As you would like people to do to you, do exactly so to them."},
{n:217,ref:"Luke 6:38",text:"Give, and it will be given to you: good measure, pressed down, shaken together, and running over."},
{n:218,ref:"1 Chronicles 29:11",text:"Yours, God, is the greatness, the power, the glory, the victory, and the majesty!"},
{n:219,ref:"Luke 12:7",text:"But the very hairs of your head are all counted. Therefore don't be afraid. You are of more value than many sparrows."},
{n:220,ref:"John 1:12",text:"But as many as received him, to them he gave the right to become God's children."},
{n:221,ref:"John 4:24",text:"God is spirit, and those who worship him must worship in spirit and truth."},
{n:222,ref:"John 6:35",text:"I am the bread of life. Whoever comes to me will not be hungry, and whoever believes in me will never be thirsty."},
{n:223,ref:"John 8:12",text:"I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life."},
{n:224,ref:"John 11:25",text:"I am the resurrection and the life. He who believes in me will still live, even if he dies."},
{n:225,ref:"John 13:34",text:"A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another."},
{n:226,ref:"John 14:27",text:"Peace I leave with you. My peace I give to you. Don't let your heart be troubled, neither let it be fearful."},
{n:227,ref:"John 15:13",text:"Greater love has no one than this, that someone lay down his life for his friends."},
{n:228,ref:"Acts 2:38",text:"Repent, and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of sins."},
{n:229,ref:"Acts 4:12",text:"There is salvation in no one else, for there is no other name under heaven given among men by which we must be saved."},
{n:230,ref:"Acts 20:35",text:"It is more blessed to give than to receive."},
{n:231,ref:"2 Timothy 4:7",text:"I have fought the good fight. I have finished the course. I have kept the faith."},
{n:232,ref:"Romans 1:16",text:"For I am not ashamed of the Good News of Christ, for it is the power of God for salvation for everyone who believes."},
{n:233,ref:"Romans 3:23",text:"For all have sinned, and fall short of the glory of God."},
{n:234,ref:"Romans 5:1",text:"Being therefore justified by faith, we have peace with God through our Lord Jesus Christ."},
{n:235,ref:"Romans 12:1",text:"Present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service."},
{n:236,ref:"Romans 12:12",text:"Rejoicing in hope; enduring in troubles; continuing steadfastly in prayer."},
{n:237,ref:"Romans 12:21",text:"Don't be overcome by evil, but overcome evil with good."},
{n:238,ref:"Romans 14:8",text:"For if we live, we live to the Lord. Or if we die, we die to the Lord."},
{n:239,ref:"1 Corinthians 1:18",text:"For the word of the cross is foolishness to those who are dying, but to us who are saved it is the power of God."},
{n:240,ref:"1 Corinthians 2:9",text:"Things which an eye didn't see, and an ear didn't hear, which didn't enter into the heart of man, these God has prepared for those who love him."},
{n:241,ref:"1 Corinthians 15:58",text:"Be steadfast, immovable, always abounding in the Lord's work, because you know that your labor is not in vain in the Lord."},
{n:242,ref:"1 Corinthians 16:14",text:"Let all that you do be done in love."},
{n:243,ref:"Hebrews 6:19",text:"This hope we have as an anchor of the soul, a hope both sure and steadfast."},
{n:244,ref:"2 Corinthians 1:3-4",text:"Blessed be the Father of mercies and God of all comfort, who comforts us in all our affliction, that we may be able to comfort those who are in any affliction."},
{n:245,ref:"2 Corinthians 4:16",text:"Therefore we don't faint, but though our outward person is decaying, yet our inward person is renewed day by day."},
{n:246,ref:"2 Corinthians 4:18",text:"For the things which are seen are temporal, but the things which are not seen are eternal."},
{n:247,ref:"2 Corinthians 5:7",text:"For we walk by faith, not by sight."},
{n:248,ref:"2 Corinthians 9:7",text:"Let each man give according as he has determined in his heart, not grudgingly or under compulsion, for God loves a cheerful giver."},
{n:249,ref:"2 Corinthians 10:5",text:"We throw down every high thing that is exalted against the knowledge of God, bringing every thought into captivity to the obedience of Christ."},
{n:250,ref:"Galatians 3:28",text:"There is neither Jew nor Greek, there is neither slave nor free man, there is neither male nor female; for you are all one in Christ Jesus."},
{n:251,ref:"Galatians 5:1",text:"Stand firm therefore in the liberty by which Christ has made us free."},
{n:252,ref:"Galatians 6:2",text:"Bear one another's burdens, and so fulfill the law of Christ."},
{n:253,ref:"Ephesians 1:7",text:"In him we have our redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace."},
{n:254,ref:"Ephesians 3:20",text:"Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us."},
{n:255,ref:"Ephesians 4:2",text:"With all lowliness and humility, with patience, bearing with one another in love."},
{n:256,ref:"Ephesians 5:2",text:"Walk in love, even as Christ also loved you and gave himself up for us."},
{n:257,ref:"Philippians 2:10-11",text:"At the name of Jesus every knee should bow, and every tongue should confess that Jesus Christ is Lord, to the glory of God the Father."},
{n:258,ref:"Philippians 2:13",text:"For it is God who works in you both to will and to work, for his good pleasure."},
{n:259,ref:"Philippians 3:14",text:"I press on toward the goal for the prize of the high calling of God in Christ Jesus."},
{n:260,ref:"Philippians 4:4",text:"Rejoice in the Lord always! Again I will say, Rejoice!"},
{n:261,ref:"Colossians 1:17",text:"He is before all things, and in him all things are held together."},
{n:262,ref:"Colossians 3:12",text:"Put on therefore, as God's chosen ones, a heart of compassion, kindness, lowliness, humility, and perseverance."},
{n:263,ref:"Colossians 3:13",text:"Bearing with one another, and forgiving each other, if any man has a complaint against any."},
{n:264,ref:"Colossians 3:15",text:"And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful."},
{n:265,ref:"1 Thessalonians 5:11",text:"Therefore exhort one another, and build each other up, even as you also do."},
{n:266,ref:"2 Thessalonians 3:3",text:"But the Lord is faithful, who will establish you and guard you from the evil one."},
{n:267,ref:"Genesis 1:27",text:"God created man in his own image. In God's image he created him; male and female he created them."},
{n:268,ref:"1 Timothy 4:12",text:"Let no man despise your youth; but be an example to those who believe, in word, in your way of life, in love, in spirit, in faith, in purity."},
{n:269,ref:"1 Timothy 6:12",text:"Fight the good fight of faith. Take hold of the eternal life to which you were called."},
{n:270,ref:"2 Timothy 1:9",text:"Who saved us and called us with a holy calling, not according to our works, but according to his own purpose and grace."},
{n:271,ref:"2 Timothy 2:15",text:"Give diligence to present yourself approved by God, a workman who doesn't need to be ashamed, properly handling the Word of Truth."},
{n:272,ref:"Titus 3:5",text:"Not by works of righteousness which we did ourselves, but according to his mercy, he saved us."},
{n:273,ref:"Hebrews 10:23",text:"Let's hold fast the confession of our hope without wavering; for he who promised is faithful."},
{n:274,ref:"Hebrews 10:24",text:"Let's consider how to provoke one another to love and good works."},
{n:275,ref:"Hebrews 11:6",text:"Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists."},
{n:276,ref:"Hebrews 12:11",text:"All chastening seems for the present to be not joyous but grievous; yet afterward it yields the peaceful fruit of righteousness."},
{n:277,ref:"Hebrews 13:5",text:"Be free from the love of money, content with such things as you have, for he has said, I will in no way leave you, neither will I in any way forsake you."},
{n:278,ref:"James 1:12",text:"Blessed is a person who endures temptation, for when he has been approved, he will receive the crown of life."},
{n:279,ref:"James 1:17",text:"Every good gift and every perfect gift is from above, coming down from the Father of lights."},
{n:280,ref:"James 2:17",text:"Even so faith, if it has no works, is dead in itself."},
{n:281,ref:"James 5:16",text:"Confess your offenses to one another, and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective."},
{n:282,ref:"1 Peter 1:3",text:"According to his great mercy he caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead."},
{n:283,ref:"1 Peter 3:15",text:"Always be ready to give an answer to everyone who asks you a reason concerning the hope that is in you, with humility and fear."},
{n:284,ref:"1 Peter 4:8",text:"Above all things be earnest in your love among yourselves, for love covers a multitude of sins."},
{n:285,ref:"1 Peter 5:10",text:"But may the God of all grace, who called you to his eternal glory by Christ Jesus, perfect, establish, strengthen, and settle you."},
{n:286,ref:"2 Peter 1:3",text:"His divine power has granted to us all things that pertain to life and godliness."},
{n:287,ref:"1 John 2:15",text:"Don't love the world or the things that are in the world."},
{n:288,ref:"1 John 3:18",text:"My little children, let's not love in word only, or with the tongue only, but in deed and truth."},
{n:289,ref:"1 John 5:14",text:"This is the boldness which we have toward him, that if we ask anything according to his will, he listens to us."},
{n:290,ref:"3 John 1:4",text:"I have no greater joy than this: to hear about my children walking in truth."},
{n:291,ref:"Jude 1:24",text:"Now to him who is able to keep them from stumbling, and to present you faultless before the presence of his glory in great joy."},
{n:292,ref:"Revelation 1:8",text:"I am the Alpha and the Omega, says the Lord God, who is and who was and who is to come, the Almighty."},
{n:293,ref:"Revelation 21:5",text:"He who sits on the throne said, Behold, I am making all things new."},
{n:294,ref:"Revelation 22:13",text:"I am the Alpha and the Omega, the First and the Last, the Beginning and the End."},
{n:295,ref:"Genesis 28:15",text:"Behold, I am with you, and will keep you, wherever you go."},
{n:296,ref:"Genesis 50:20",text:"As for you, you meant evil against me, but God meant it for good."},
{n:297,ref:"Matthew 6:14",text:"For if you forgive men their trespasses, your heavenly Father will also forgive you."},
{n:298,ref:"Exodus 20:12",text:"Honor your father and your mother, that your days may be long in the land which God your God gives you."},
{n:299,ref:"Leviticus 26:12",text:"I will walk among you, and will be your God, and you shall be my people."},
{n:300,ref:"Deuteronomy 7:9",text:"Know therefore that God your God himself is God, the faithful God, who keeps covenant and loving kindness."},
{n:301,ref:"Deuteronomy 30:19",text:"I have set before you life and death, the blessing and the curse. Therefore choose life, that you may live."},
{n:302,ref:"Ruth 1:16",text:"Where you go, I will go; and where you stay, I will stay. Your people shall be my people, and your God my God."},
{n:303,ref:"1 Samuel 12:24",text:"Only fear God, and serve him in truth with all your heart; for consider what great things he has done for you."},
{n:304,ref:"2 Samuel 22:31",text:"As for God, his way is perfect. God's word is tested. He is a shield to all those who take refuge in him."},
{n:305,ref:"1 Kings 8:56",text:"Blessed be God, who has given rest to his people Israel, according to all that he promised."},
{n:306,ref:"1 Chronicles 16:11",text:"Seek God and his strength. Seek his face forever more."},
{n:307,ref:"1 Chronicles 16:34",text:"Oh give thanks to God, for he is good, for his loving kindness endures forever."},
{n:308,ref:"2 Chronicles 15:7",text:"But you be strong! Don't let your hands be slack, for your work will be rewarded."},
{n:309,ref:"2 Chronicles 20:15",text:"Don't be afraid, and don't be dismayed because of this great multitude; for the battle is not yours, but God's."},
{n:310,ref:"Ezra 10:4",text:"Arise, for the matter belongs to you and we are with you. Be courageous, and do it."},
{n:311,ref:"Job 23:10",text:"But he knows the way that I take. When he has tried me, I will come out like gold."},
{n:312,ref:"Job 42:2",text:"I know that you can do all things, and that no purpose of yours can be restrained."},
{n:313,ref:"Psalm 3:3",text:"But you, God, are a shield around me, my glory, and the one who lifts up my head."},
{n:314,ref:"Psalm 4:8",text:"In peace I will both lay myself down and sleep, for you alone, God, make me live in safety."},
{n:315,ref:"Psalm 5:3",text:"God, in the morning you shall hear my voice. In the morning I will lay my requests before you, and will watch expectantly."},
{n:316,ref:"Psalm 9:9",text:"God will also be a high tower for the oppressed; a high tower in times of trouble."},
{n:317,ref:"Psalm 9:10",text:"Those who know your name will put their trust in you, for you, God, have not forsaken those who seek you."},
{n:318,ref:"Psalm 13:5",text:"But I trust in your loving kindness. My heart rejoices in your salvation."},
{n:319,ref:"Psalm 20:7",text:"Some trust in chariots, and some in horses, but we trust in the name of God our God."},
{n:320,ref:"Psalm 25:4",text:"Show me your ways, God. Teach me your paths."},
{n:321,ref:"Psalm 29:11",text:"God will give strength to his people. God will bless his people with peace."},
{n:322,ref:"Psalm 31:3",text:"For you are my rock and my fortress, therefore for your name's sake lead me and guide me."},
{n:323,ref:"Psalm 33:20",text:"Our soul has waited for God. He is our help and our shield."},
{n:324,ref:"Psalm 34:1",text:"I will bless God at all times. His praise will always be in my mouth."},
{n:325,ref:"Psalm 34:19",text:"Many are the afflictions of the righteous, but God delivers him out of them all."},
{n:326,ref:"Psalm 36:5",text:"Your loving kindness, God, is in the heavens. Your faithfulness reaches to the skies."},
{n:327,ref:"Psalm 37:5",text:"Commit your way to God. Trust also in him, and he will do this."},
{n:328,ref:"Psalm 37:7",text:"Rest in God, and wait patiently for him."},
{n:329,ref:"Psalm 41:3",text:"God will sustain him on his sickbed, and restore him from his bed of illness."},
{n:330,ref:"Psalm 44:8",text:"In God we have made our boast all day long, we will give thanks to your name forever."},
{n:331,ref:"Psalm 47:1",text:"Oh clap your hands, all you nations. Shout to God with the voice of triumph!"},
{n:332,ref:"Psalm 50:15",text:"Call on me in the day of trouble. I will deliver you, and you will honor me."},
{n:333,ref:"Psalm 55:17",text:"Evening, morning, and at noon, I will cry out in distress. He will hear my voice."},
{n:334,ref:"Psalm 57:1",text:"Be merciful to me, God, be merciful to me, for my soul takes refuge in you."},
{n:335,ref:"Psalm 59:16",text:"But I will sing of your strength. Yes, I will sing aloud of your loving kindness in the morning."},
{n:336,ref:"Psalm 61:2",text:"From the end of the earth I will call to you when my heart is overwhelmed. Lead me to the rock that is higher than I."},
{n:337,ref:"Psalm 66:19",text:"But most certainly, God has listened. He has heard the voice of my prayer."},
{n:338,ref:"Psalm 68:19",text:"Blessed be the Lord, who daily bears our burdens, even the God who is our salvation."},
{n:339,ref:"Psalm 72:18",text:"Praise be to God, the God of Israel, who alone does marvelous deeds."},
{n:340,ref:"Psalm 77:14",text:"You are the God who does wonders. You have made your strength known among the peoples."},
{n:341,ref:"Psalm 86:5",text:"For you, Lord, are good, and ready to forgive, abundant in loving kindness to all those who call on you."},
{n:342,ref:"Psalm 89:1",text:"I will sing of the loving kindness of God forever. With my mouth, I will make known your faithfulness to all generations."},
{n:343,ref:"Psalm 92:1",text:"It is a good thing to give thanks to God, to sing praises to your name, Most High."},
{n:344,ref:"Psalm 95:1",text:"Oh come, let's sing to God. Let's shout aloud to the rock of our salvation!"},
{n:345,ref:"Psalm 96:1",text:"Sing to God a new song! Sing to God, all the earth."},
{n:346,ref:"Isaiah 25:1",text:"God, you are my God. I will exalt you! I will praise your name, for you have done wonderful things."},
{n:347,ref:"Psalm 100:1",text:"Shout for joy to God, all you lands!"},
{n:348,ref:"Psalm 100:3",text:"Know that God, he is God. It is he who has made us, and we are his. We are his people, and the sheep of his pasture."},
{n:349,ref:"Psalm 103:8",text:"God is merciful and gracious, slow to anger, and abundant in loving kindness."},
{n:350,ref:"Psalm 111:10",text:"The fear of God is the beginning of wisdom. All those who do his work have a good understanding."},
{n:351,ref:"Psalm 116:1",text:"I love God, because he listens to my voice, and my cries for mercy."},
{n:352,ref:"Psalm 119:114",text:"You are my hiding place and my shield. I hope in your word."},
{n:353,ref:"Psalm 119:130",text:"The entrance of your words gives light. It gives understanding to the simple."},
{n:354,ref:"Psalm 121:3",text:"He will not allow your foot to be moved. He who keeps you will not slumber."},
{n:355,ref:"Psalm 130:5",text:"I wait for God. My soul waits. I hope in his word."},
{n:356,ref:"Psalm 138:3",text:"In the day that I called, you answered me. You encouraged me with strength in my soul."},
{n:357,ref:"Psalm 139:7",text:"Where could I go from your Spirit? Or where could I flee from your presence?"},
{n:358,ref:"Psalm 139:16",text:"Your eyes saw my body. In your book they were all written, the days that were ordained for me."},
{n:359,ref:"Psalm 141:2",text:"Let my prayer be set before you like incense; the lifting up of my hands like the evening sacrifice."},
{n:360,ref:"Psalm 143:10",text:"Teach me to do your will, for you are my God. Your Spirit is good. Lead me in the land of uprightness."},
{n:361,ref:"Psalm 145:9",text:"God is good to all. His tender mercies are over all his works."},
{n:362,ref:"Psalm 146:5",text:"Happy is he who has the God of Jacob for his help, whose hope is in God, his God."},
{n:363,ref:"Psalm 147:5",text:"Great is our Lord, and mighty in power. His understanding is infinite."},
{n:364,ref:"Psalm 150:6",text:"Let everything that has breath praise God. Praise God!"},
{n:365,ref:"Revelation 22:21",text:"The grace of the Lord Jesus Christ be with all the saints. Amen."}
];
